### ISSUE TITLE
Feature Request: Modification to Sort filter to exclude personally-created playlists

### ISSUE THREAD

**Issue by dhry** [Chordian/deepsid#8]
I have a request. When using the sort filter for All/Personal I note that choosing Personal basically kills off all items except HVSC and Compute's Gazette. I'm wondering whether you could include the other non-personal playlists in the list of items that remain when choosing Personal. $11 Music Compo, X2016 etc aren't personal playlists but factual collections. Or perhaps if you could include a third option. Something like this:

**All** (includes HVSC + Compute, democompo collections, made-public and private playlists)
**Master and Democompo Collections only**
**HVSC+Compute only**

I'm just looking for a way to exclude playlists that people are making public. I don't mind seeing the democompo compilations, or of course the master compilations, but the contents of individual playlists are a crapshoot and IMO have already started to mess up the list of items shown in the root folder. Obviously I want my own personal favourites playlist displayed at all times though. :-)

**Comment by Chordian** [comment]
Thanks for the interest in improving DeepSID. =)

The `Personal` option should show HVSC + CGSC + Your own public playlists + Your own personal playlists. Do you have any of the latter and they don't show up when selecting this option? If so, that's a bug. It's specifically designed to _only_ filter out public playlists from other people.

Regarding the collections, they are actually still public playlists. If you enter one of them, say, $11 Music Compo, you can see below its title that it was a playlist I made. This was once a custom server folder, but I since converted it as I'm trying to "phase out" these type of folders so that only HVSC and CGSC remain as actually physical folders on the server. Now that HVSC version 70 has been released I also plan to convert the last two custom server folders for Datastorm 2018 and JCH's Personal Collection to public playlists.

I can see it might be interesting to show playlists that are based on good collections, but there's currently no difference between them and those "favorite"-type playlists. It's the same type.

I actually thought about adding a different kind of filtering in the style of what you do on Reddit, where you can right-click a public playlist and "hide" it. Also, the reason I stopped adding competition collections was because I have been thinking, maybe I could pull these out of CSDb later and show them in a better way? Just as with the CSDb tab pages, it might be best if I can make some code do all the work instead of spending years creating collection folders.

**Comment by Chordian** [comment]
I actually kind of agree with the favorites part, the first time I saw those pop up I was thinking, "Why do you need us to see those?" - on the other hand, I've also had users tell me they like to check this stuff out. I think people should be allowed to publish whatever they want as long as they're genuine and not just trolling around.

But yeah, more filter options might be nice. I'll make a note of some kind of extra flag and filter option for public playlists that are considered collections (or otherwise "non-personal" in nature).

**Comment by Chordian** [comment]
I've now added a `Common` filter option in the root. Select this to show the HVSC and CGSC collection folders along with common collection/competition playlists, plus of course your personal playlists.

In other words, the new option filters out public playlists that are personal in nature, such as e.g. lists of favorites.

**Comment by dhry** [comment]
This is exactly - EXACTLY - what I was looking for. Thanks Jens!
